# -*- coding: utf-8 -*-
import sys
from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5.QtWidgets import QMessageBox

import time
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import os
import math
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as Canvas
from matplotlib.figure import Figure
from PyQt5.QtGui import QTextCursor
from pip._internal import req
import requests
from ExchangePlaceClasses import Prosumer, Asset

import json
import Scheduling, Supervision, GenericExchangePlace, Prediction

global dataEnv
with open("./files/env.json") as json_file:
    dataEnv = json.load(json_file)
    
uifile_1 = 'login.ui'
form_1, base_1 = uic.loadUiType(uifile_1)
uifile_2 = 'Exchange.ui'
form_2, base_2 = uic.loadUiType(uifile_2)
import images_rc

##############

class MplCanvas(Canvas):
    def __init__(self):
        self.fig = Figure()
        self.ax = self.fig.add_subplot(111)
        Canvas.__init__(self, self.fig)
        Canvas.setSizePolicy(self, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        Canvas.updateGeometry(self)

#----------------------------------------
#----------------------------------------
        
class MplWidget(QtWidgets.QWidget):
    def __init__(self, parent=None):
        QtWidgets.QWidget.__init__(self, parent)   
        self.canvas = MplCanvas()                  
        self.vbl = QtWidgets.QVBoxLayout()         
        self.vbl.addWidget(self.canvas)
        self.setLayout(self.vbl)
######################################

class Exchange(base_2, form_2):
    """consumption=[]
    production=[]"""
    
    __instance = None
    def __init__(self):
        """ Virtually private constructor. """
        if Exchange.__instance != None:
            raise Exception("This class is a singleton!")
        else:
            super(base_2, self).__init__()
            self.setupUi(self) 
            Supervision.weather_data(self)
            Supervision.clock(self)
            self.battery=''
            self.ssh=''
            #Supervision.balance(self)
        Exchange.__instance = self

    @staticmethod 
    def getInstance():
        """ Static access method. """
        if Exchange.__instance == None:
            Exchange()
        return Exchange.__instance 

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainStackWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.MainStackWidget.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.MainStackWidget.setMinimumSize(QtCore.QSize(1024, 600))
        self.MainStackWidget.setMaximumSize(QtCore.QSize(1024, 600))
        self.MainStackWidget.setStyleSheet("background-color: rgb(255, 255, 255);color: rgb(255, 255, 255);")
        self.MainStackWidget.setMidLineWidth(1)
        self.MainStackWidget.setObjectName("MainStackWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.page_0.setObjectName("page_0")
        self.login = QtWidgets.QLineEdit(self.page_0)
        self.login.setGeometry(QtCore.QRect(190, 390, 250, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.login.setFont(font)
        self.login.setStyleSheet("border-radius: 15px;border: 2px solid gray;background-color: rgb(226, 226, 226);")
        self.login.setObjectName("login")
        self.loginbt = QtWidgets.QPushButton(self.page_0)
        self.loginbt.setGeometry(QtCore.QRect(650, 500, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(22)
        self.loginbt.setFont(font)
        self.loginbt.setStyleSheet("background-color: rgb(56, 125, 197);border-radius: 20px;color: rgb(255, 255, 255);")
        self.loginbt.setObjectName("loginbt")
        self.label_10 = QtWidgets.QLabel(self.page_0)
        self.label_10.setGeometry(QtCore.QRect(510, 400, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(22)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.page_0)
        self.label_12.setGeometry(QtCore.QRect(212, 250, 600, 100))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(48)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label = QtWidgets.QLabel(self.page_0)
        self.label.setGeometry(QtCore.QRect(50, 400, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.password = QtWidgets.QLineEdit(self.page_0)
        self.password.setGeometry(QtCore.QRect(710, 400, 250, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.password.setFont(font)
        self.password.setStyleSheet("border-radius: 15px;border: 2px solid gray;background-color: rgb(226, 226, 226);")
        self.password.setObjectName("password")
        self.label_18 = QtWidgets.QLabel(self.page_0)
        self.label_18.setGeometry(QtCore.QRect(730, 40, 250, 150))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("C:\\eclipse-workspace\\AppEMTS\\EMTS_AutomaticModeConsumer\\../../../Users/a.gassara/.designer/backup/images/sofrecomlogo.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_13 = QtWidgets.QLabel(self.page_0)
        self.label_13.setGeometry(QtCore.QRect(50, 40, 250, 150))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("C:\\eclipse-workspace\\AppEMTS\\EMTS_AutomaticModeConsumer\\../../../Users/a.gassara/.designer/backup/images/centrelogo.jpg"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.exitAppbtn = QtWidgets.QPushButton(self.page_0)
        self.exitAppbtn.setGeometry(QtCore.QRect(810, 500, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(22)
        self.exitAppbtn.setFont(font)
        self.exitAppbtn.setStyleSheet("background-color: rgb(56, 125, 197);border-radius: 20px;color: rgb(255, 255, 255);")
        self.exitAppbtn.setObjectName("exitAppbtn")
        self.MainStackWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.SolarPanel = QtWidgets.QWidget(self.page_1)
        self.SolarPanel.setGeometry(QtCore.QRect(10, 98, 661, 201))
        self.SolarPanel.setStyleSheet("background-color: rgb(255, 255, 255);border:2px solid rgb(125, 172, 56);")
        self.SolarPanel.setObjectName("SolarPanel")
        self.label_11 = QtWidgets.QLabel(self.SolarPanel)
        self.label_11.setGeometry(QtCore.QRect(20, 80, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(0, 0, 127);border:0px ;")
        self.label_11.setObjectName("label_11")
        self.solde = QtWidgets.QLabel(self.SolarPanel)
        self.solde.setGeometry(QtCore.QRect(50, 130, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.solde.setFont(font)
        self.solde.setStyleSheet("border-color: rgb(255, 255, 255);color:rgb(0, 0, 0)")
        self.solde.setObjectName("solde")
        self.bienvenue = QtWidgets.QLabel(self.SolarPanel)
        self.bienvenue.setGeometry(QtCore.QRect(10, 14, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.bienvenue.setFont(font)
        self.bienvenue.setStyleSheet("color: rgb(0, 0, 0);border:0px;")
        self.bienvenue.setObjectName("bienvenue")
        self.label_28 = QtWidgets.QLabel(self.SolarPanel)
        self.label_28.setGeometry(QtCore.QRect(230, 90, 71, 71))
        self.label_28.setStyleSheet("color: rgb(0, 0, 0);border:0px;")
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap("C:\\eclipse-workspace\\AppEMTS\\EMTS_AutomaticModeConsumer\\images/money.jpg"))
        self.label_28.setScaledContents(True)
        self.label_28.setObjectName("label_28")
        self.label_81 = QtWidgets.QLabel(self.SolarPanel)
        self.label_81.setGeometry(QtCore.QRect(409, 80, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_81.setFont(font)
        self.label_81.setStyleSheet("color: rgb(0, 0, 127);border:0px ;")
        self.label_81.setObjectName("label_81")
        self.mode = QtWidgets.QLabel(self.SolarPanel)
        self.mode.setGeometry(QtCore.QRect(449, 120, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setItalic(False)
        self.mode.setFont(font)
        self.mode.setStyleSheet("border:0px ;color: rbg(0,0,0);")
        self.mode.setObjectName("mode")
        self.label_6 = QtWidgets.QLabel(self.SolarPanel)
        self.label_6.setGeometry(QtCore.QRect(403, 19, 31, 31))
        self.label_6.setStyleSheet("border:0px ;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("C:\\eclipse-workspace\\AppEMTS\\EMTS_AutomaticModeConsumer\\images/loc.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.Localisation = QtWidgets.QLabel(self.SolarPanel)
        self.Localisation.setGeometry(QtCore.QRect(432, 22, 81, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.Localisation.setFont(font)
        self.Localisation.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.Localisation.setAlignment(QtCore.Qt.AlignCenter)
        self.Localisation.setObjectName("Localisation")
        self.hour = QtWidgets.QLabel(self.SolarPanel)
        self.hour.setGeometry(QtCore.QRect(519, 27, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(18)
        self.hour.setFont(font)
        self.hour.setStyleSheet("color:rgb(0, 0, 0);border:0px ;")
        self.hour.setObjectName("hour")
        self.Battery = QtWidgets.QWidget(self.page_1)
        self.Battery.setGeometry(QtCore.QRect(10, 310, 311, 241))
        self.Battery.setStyleSheet("background-color: rgb(255, 255, 255);border:2px solid rgb(125, 172, 56);")
        self.Battery.setObjectName("Battery")
        self.label_2 = QtWidgets.QLabel(self.Battery)
        self.label_2.setGeometry(QtCore.QRect(4, 13, 281, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"border:3px solid white;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setIndent(-2)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.Battery)
        self.label_7.setGeometry(QtCore.QRect(20, 74, 171, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(0, 0, 127);border:1px solid rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.pvPower = QtWidgets.QLCDNumber(self.Battery)
        self.pvPower.setGeometry(QtCore.QRect(5, 130, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pvPower.setFont(font)
        self.pvPower.setStyleSheet("color:rgb(0, 0, 0);border:1px solid rgb(255, 255, 255);")
        self.pvPower.setDigitCount(6)
        self.pvPower.setProperty("value", 0.0)
        self.pvPower.setObjectName("pvPower")
        self.label_8 = QtWidgets.QLabel(self.Battery)
        self.label_8.setGeometry(QtCore.QRect(150, 143, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(0, 0, 0);border:1px solid rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.solarIMG = QtWidgets.QLabel(self.Battery)
        self.solarIMG.setGeometry(QtCore.QRect(206, 50, 91, 71))
        self.solarIMG.setStyleSheet("border:1px solid rgb(255, 255, 255);")
        self.solarIMG.setText("")
        self.solarIMG.setPixmap(QtGui.QPixmap("C:\\eclipse-workspace\\AppEMTS\\EMTS_AutomaticModeConsumer\\images/solar.png"))
        self.solarIMG.setScaledContents(True)
        self.solarIMG.setObjectName("solarIMG")
        self.weather = QtWidgets.QWidget(self.page_1)
        self.weather.setGeometry(QtCore.QRect(680, 99, 341, 201))
        self.weather.setStyleSheet("background-color: rgb(255, 255, 255);border:2px solid rgb(125, 172, 56);")
        self.weather.setObjectName("weather")
        self.WeatherImage = QtWidgets.QLabel(self.weather)
        self.WeatherImage.setGeometry(QtCore.QRect(40, 44, 41, 41))
        self.WeatherImage.setStyleSheet("border:0px ;")
        self.WeatherImage.setText("")
        self.WeatherImage.setPixmap(QtGui.QPixmap("C:\\eclipse-workspace\\AppEMTS\\EMTS_AutomaticModeConsumer\\images/01d.png"))
        self.WeatherImage.setScaledContents(True)
        self.WeatherImage.setObjectName("WeatherImage")
        self.label_106 = QtWidgets.QLabel(self.weather)
        self.label_106.setGeometry(QtCore.QRect(292, 48, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_106.setFont(font)
        self.label_106.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.label_106.setObjectName("label_106")
        self.temperature = QtWidgets.QLCDNumber(self.weather)
        self.temperature.setGeometry(QtCore.QRect(242, 60, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.temperature.setFont(font)
        self.temperature.setStyleSheet("color:rgb(0, 0, 0);border:0px ;")
        self.temperature.setDigitCount(2)
        self.temperature.setProperty("value", 30.0)
        self.temperature.setObjectName("temperature")
        self.description = QtWidgets.QLabel(self.weather)
        self.description.setGeometry(QtCore.QRect(27, 94, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.description.setFont(font)
        self.description.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.description.setObjectName("description")
        self.humidity = QtWidgets.QLabel(self.weather)
        self.humidity.setGeometry(QtCore.QRect(14, 150, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.humidity.setFont(font)
        self.humidity.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.humidity.setAlignment(QtCore.Qt.AlignCenter)
        self.humidity.setObjectName("humidity")
        self.label_4 = QtWidgets.QLabel(self.weather)
        self.label_4.setGeometry(QtCore.QRect(18, 9, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);border:0px;")
        self.label_4.setObjectName("label_4")
        self.label1 = QtWidgets.QLabel(self.weather)
        self.label1.setGeometry(QtCore.QRect(211, 150, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label1.setFont(font)
        self.label1.setStyleSheet("color:black;border:0px;")
        self.label1.setObjectName("label1")
        self.backbtn = QtWidgets.QPushButton(self.page_1)
        self.backbtn.setGeometry(QtCore.QRect(910, 20, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(22)
        self.backbtn.setFont(font)
        self.backbtn.setStyleSheet("background-color:rgb(121, 121, 121);border-radius: 20px;color: rgb(255, 255, 255);")
        self.backbtn.setObjectName("backbtn")
        self.Grid = QtWidgets.QWidget(self.page_1)
        self.Grid.setGeometry(QtCore.QRect(680, 310, 341, 241))
        self.Grid.setStyleSheet("background-color: rgb(255, 255, 255);border:2px solid rgb(125, 172, 56);")
        self.Grid.setObjectName("Grid")
        self.gridIMG = QtWidgets.QLabel(self.Grid)
        self.gridIMG.setGeometry(QtCore.QRect(200, 50, 111, 91))
        self.gridIMG.setStyleSheet("border:0px ;")
        self.gridIMG.setText("")
        self.gridIMG.setPixmap(QtGui.QPixmap("C:\\eclipse-workspace\\AppEMTS\\EMTS_AutomaticModeConsumer\\images/consCollective.png"))
        self.gridIMG.setScaledContents(True)
        self.gridIMG.setObjectName("gridIMG")
        self.label_67 = QtWidgets.QLabel(self.Grid)
        self.label_67.setGeometry(QtCore.QRect(20, 160, 251, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setStyleSheet("color: rgb(0, 0, 127);border:0px ;")
        self.label_67.setObjectName("label_67")
        self.label_74 = QtWidgets.QLabel(self.Grid)
        self.label_74.setGeometry(QtCore.QRect(20, 60, 141, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_74.setFont(font)
        self.label_74.setStyleSheet("color: rgb(0, 0, 127);border:0px ;")
        self.label_74.setObjectName("label_74")
        self.outgoingPower = QtWidgets.QLCDNumber(self.Grid)
        self.outgoingPower.setGeometry(QtCore.QRect(10, 113, 90, 25))
        self.outgoingPower.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.outgoingPower.setDigitCount(7)
        self.outgoingPower.setProperty("value", 0.0)
        self.outgoingPower.setObjectName("outgoingPower")
        self.ingoingPower = QtWidgets.QLCDNumber(self.Grid)
        self.ingoingPower.setGeometry(QtCore.QRect(10, 197, 90, 25))
        self.ingoingPower.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.ingoingPower.setDigitCount(7)
        self.ingoingPower.setProperty("value", 0.0)
        self.ingoingPower.setObjectName("ingoingPower")
        self.label_77 = QtWidgets.QLabel(self.Grid)
        self.label_77.setGeometry(QtCore.QRect(120, 200, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_77.setFont(font)
        self.label_77.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.label_77.setObjectName("label_77")
        self.label_82 = QtWidgets.QLabel(self.Grid)
        self.label_82.setGeometry(QtCore.QRect(120, 112, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_82.setFont(font)
        self.label_82.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.label_82.setObjectName("label_82")
        self.label_78 = QtWidgets.QLabel(self.Grid)
        self.label_78.setGeometry(QtCore.QRect(10, 9, 291, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_78.setFont(font)
        self.label_78.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.label_78.setObjectName("label_78")
        self.Home = QtWidgets.QWidget(self.page_1)
        self.Home.setGeometry(QtCore.QRect(330, 310, 341, 241))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Home.setFont(font)
        self.Home.setStyleSheet("background-color: rgb(255, 255, 255);border:2px solid rgb(125, 172, 56);")
        self.Home.setObjectName("Home")
        self.label_92 = QtWidgets.QLabel(self.Home)
        self.label_92.setGeometry(QtCore.QRect(160, 110, 21, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_92.setFont(font)
        self.label_92.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.label_92.setObjectName("label_92")
        self.houseIMG = QtWidgets.QLabel(self.Home)
        self.houseIMG.setGeometry(QtCore.QRect(210, 30, 111, 91))
        self.houseIMG.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.houseIMG.setText("")
        self.houseIMG.setPixmap(QtGui.QPixmap("C:\\eclipse-workspace\\AppEMTS\\EMTS_AutomaticModeConsumer\\images/withGrid.png"))
        self.houseIMG.setScaledContents(True)
        self.houseIMG.setObjectName("houseIMG")
        self.label_85 = QtWidgets.QLabel(self.Home)
        self.label_85.setGeometry(QtCore.QRect(11, 17, 211, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_85.setFont(font)
        self.label_85.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.label_85.setObjectName("label_85")
        self.label_88 = QtWidgets.QLabel(self.Home)
        self.label_88.setGeometry(QtCore.QRect(20, 67, 161, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_88.setFont(font)
        self.label_88.setStyleSheet("color: rgb(0, 0, 127);border:0px ;")
        self.label_88.setObjectName("label_88")
        self.consommationPower = QtWidgets.QLCDNumber(self.Home)
        self.consommationPower.setGeometry(QtCore.QRect(26, 188, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.consommationPower.setFont(font)
        self.consommationPower.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.consommationPower.setDigitCount(5)
        self.consommationPower.setProperty("value", 0.0)
        self.consommationPower.setObjectName("consommationPower")
        self.label_24 = QtWidgets.QLabel(self.Home)
        self.label_24.setGeometry(QtCore.QRect(20, 159, 201, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: rgb(0, 0, 127);border:0px ;")
        self.label_24.setObjectName("label_24")
        self.feededPower = QtWidgets.QLCDNumber(self.Home)
        self.feededPower.setGeometry(QtCore.QRect(30, 100, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.feededPower.setFont(font)
        self.feededPower.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.feededPower.setObjectName("feededPower")
        self.label_34 = QtWidgets.QLabel(self.Home)
        self.label_34.setGeometry(QtCore.QRect(162, 192, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.label_34.setObjectName("label_34")
        self.label_17 = QtWidgets.QLabel(self.page_1)
        self.label_17.setGeometry(QtCore.QRect(0, 0, 1021, 91))
        self.label_17.setStyleSheet("background-image: url(:/images/banniere1.png);")
        self.label_17.setText("")
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.MainStackWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.graphWidget = MplWidget(self.page_2)
        self.graphWidget.setGeometry(QtCore.QRect(10, 120, 871, 391))
        self.graphWidget.setObjectName("graphWidget")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_5.setObjectName("label_5")
        self.label_20 = QtWidgets.QLabel(self.page_2)
        self.label_20.setGeometry(QtCore.QRect(520, 97, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("C:\\eclipse-workspace\\AppEMTS\\EMTS_AutomaticModeConsumer\\images/01d.png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        self.label_22 = QtWidgets.QLabel(self.page_2)
        self.label_22.setGeometry(QtCore.QRect(286, 105, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.page_2)
        self.label_23.setGeometry(QtCore.QRect(251, 105, 31, 31))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("C:\\eclipse-workspace\\AppEMTS\\EMTS_AutomaticModeConsumer\\images/loc.jpg"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.planificationButton = QtWidgets.QPushButton(self.page_2)
        self.planificationButton.setGeometry(QtCore.QRect(570, 510, 181, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.planificationButton.setFont(font)
        self.planificationButton.setStyleSheet("color:rgb(0, 0, 0); background-color:rgb(218, 218, 218);border-radius:5px;")
        self.planificationButton.setObjectName("planificationButton")
        self.label_21 = QtWidgets.QLabel(self.page_2)
        self.label_21.setGeometry(QtCore.QRect(10, 490, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_21.setObjectName("label_21")
        self.label_26 = QtWidgets.QLabel(self.page_2)
        self.label_26.setGeometry(QtCore.QRect(0, 0, 1031, 91))
        self.label_26.setStyleSheet("background-image:url(:/images/banniere1.png)")
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setGeometry(QtCore.QRect(0, 520, 281, 41))
        self.label_9.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_9.setObjectName("label_9")
        self.energyBalance = QtWidgets.QLCDNumber(self.page_2)
        self.energyBalance.setGeometry(QtCore.QRect(290, 517, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.energyBalance.setFont(font)
        self.energyBalance.setStyleSheet("color:rgb(0, 0, 0);border:0px ;")
        self.energyBalance.setProperty("value", 10.0)
        self.energyBalance.setProperty("intValue", 10)
        self.energyBalance.setObjectName("energyBalance")
        self.MainStackWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.tableWidget = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget.setGeometry(QtCore.QRect(50, 140, 461, 401))
        self.tableWidget.setStyleSheet("color:rgb(0, 0, 0);background-color:rgb(255, 255, 255);")
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setRowCount(24)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(20, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(21, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(22, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(23, 0, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(113)
        self.tableWidget.verticalHeader().setVisible(False)
        self.label_15 = QtWidgets.QLabel(self.page_3)
        self.label_15.setGeometry(QtCore.QRect(20, 100, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_15.setObjectName("label_15")
        self.label_19 = QtWidgets.QLabel(self.page_3)
        self.label_19.setGeometry(QtCore.QRect(549, 145, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(0, 0, 0)")
        self.label_19.setObjectName("label_19")
        self.contractslistView = QtWidgets.QListView(self.page_3)
        self.contractslistView.setGeometry(QtCore.QRect(549, 200, 381, 341))
        self.contractslistView.setStyleSheet("color:rgb(0, 0, 0)")
        self.contractslistView.setObjectName("contractslistView")
        self.label_25 = QtWidgets.QLabel(self.page_3)
        self.label_25.setGeometry(QtCore.QRect(0, 0, 1021, 91))
        self.label_25.setStyleSheet("background-image: url(:/images/banniere1.png);")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.label_37 = QtWidgets.QLabel(self.page_3)
        self.label_37.setGeometry(QtCore.QRect(830, 130, 81, 61))
        self.label_37.setText("")
        self.label_37.setPixmap(QtGui.QPixmap("C:\\eclipse-workspace\\AppEMTS\\EMTS_AutomaticModeConsumer\\images/contract.png"))
        self.label_37.setScaledContents(True)
        self.label_37.setObjectName("label_37")
        self.MainStackWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_29 = QtWidgets.QLabel(self.page_4)
        self.label_29.setGeometry(QtCore.QRect(0, 0, 1021, 91))
        self.label_29.setStyleSheet("background-image: url(:/images/banniere1.png);")
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.page_4)
        self.label_30.setGeometry(QtCore.QRect(30, 110, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_30.setObjectName("label_30")
        self.todayTableWidget = QtWidgets.QTableWidget(self.page_4)
        self.todayTableWidget.setGeometry(QtCore.QRect(30, 160, 421, 381))
        self.todayTableWidget.setStyleSheet("color:rgb(0, 0, 0)")
        self.todayTableWidget.setFrameShadow(QtWidgets.QFrame.Plain)
        self.todayTableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.todayTableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.todayTableWidget.setRowCount(24)
        self.todayTableWidget.setObjectName("todayTableWidget")
        self.todayTableWidget.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.todayTableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(19, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(20, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(21, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(22, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTableWidget.setItem(23, 0, item)
        self.todayTableWidget.horizontalHeader().setVisible(True)
        self.todayTableWidget.verticalHeader().setVisible(False)
        self.todayTableWidget.verticalHeader().setMinimumSectionSize(23)
        self.label_31 = QtWidgets.QLabel(self.page_4)
        self.label_31.setGeometry(QtCore.QRect(470, 170, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("color: rgb(0, 0, 127);")
        self.label_31.setObjectName("label_31")
        self.label_14 = QtWidgets.QLabel(self.page_4)
        self.label_14.setGeometry(QtCore.QRect(471, 230, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(0, 0, 127);")
        self.label_14.setObjectName("label_14")
        self.wFeeded = QtWidgets.QLCDNumber(self.page_4)
        self.wFeeded.setGeometry(QtCore.QRect(717, 165, 71, 41))
        self.wFeeded.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.wFeeded.setObjectName("wFeeded")
        self.wConsumed = QtWidgets.QLCDNumber(self.page_4)
        self.wConsumed.setGeometry(QtCore.QRect(720, 226, 71, 31))
        self.wConsumed.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.wConsumed.setObjectName("wConsumed")
        self.label_32 = QtWidgets.QLabel(self.page_4)
        self.label_32.setGeometry(QtCore.QRect(-190, 340, 47, 13))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.page_4)
        self.label_33.setGeometry(QtCore.QRect(470, 302, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("color: rgb(0, 0, 127);")
        self.label_33.setObjectName("label_33")
        self.contractlistView = QtWidgets.QListView(self.page_4)
        self.contractlistView.setGeometry(QtCore.QRect(470, 330, 361, 201))
        self.contractlistView.setStyleSheet("color:rgb(0, 0, 0)")
        self.contractlistView.setObjectName("contractlistView")
        self.label_35 = QtWidgets.QLabel(self.page_4)
        self.label_35.setGeometry(QtCore.QRect(853, 140, 161, 111))
        self.label_35.setText("")
        self.label_35.setPixmap(QtGui.QPixmap("C:\\eclipse-workspace\\AppEMTS\\EMTS_AutomaticModeConsumer\\images/withGrid.png"))
        self.label_35.setScaledContents(True)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.page_4)
        self.label_36.setGeometry(QtCore.QRect(859, 376, 121, 111))
        self.label_36.setText("")
        self.label_36.setPixmap(QtGui.QPixmap("C:\\eclipse-workspace\\AppEMTS\\EMTS_AutomaticModeConsumer\\images/contract1.png"))
        self.label_36.setScaledContents(True)
        self.label_36.setWordWrap(True)
        self.label_36.setObjectName("label_36")
        self.MainStackWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.notificationslistView = QtWidgets.QListView(self.page_5)
        self.notificationslistView.setGeometry(QtCore.QRect(60, 160, 401, 371))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.notificationslistView.setFont(font)
        self.notificationslistView.setStyleSheet("background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);")
        self.notificationslistView.setMidLineWidth(1)
        self.notificationslistView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.notificationslistView.setObjectName("notificationslistView")
        self.label_16 = QtWidgets.QLabel(self.page_5)
        self.label_16.setGeometry(QtCore.QRect(30, 120, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_16.setObjectName("label_16")
        self.label_27 = QtWidgets.QLabel(self.page_5)
        self.label_27.setGeometry(QtCore.QRect(0, 0, 1021, 91))
        self.label_27.setStyleSheet("background-image: url(:/images/banniere1.png);")
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.MainStackWidget.addWidget(self.page_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        self.menuSupervision = QtWidgets.QMenu(self.menubar)
        self.menuSupervision.setObjectName("menuSupervision")
        self.menuTableEchange = QtWidgets.QMenu(self.menubar)
        self.menuTableEchange.setObjectName("menuTableEchange")
        self.menuNotifications = QtWidgets.QMenu(self.menubar)
        self.menuNotifications.setObjectName("menuNotifications")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMAINTENANT = QtWidgets.QAction(MainWindow)
        self.actionMAINTENANT.setObjectName("actionMAINTENANT")
        self.actionPREVIISIION = QtWidgets.QAction(MainWindow)
        self.actionPREVIISIION.setObjectName("actionPREVIISIION")
        self.actionAujourd_hui = QtWidgets.QAction(MainWindow)
        self.actionAujourd_hui.setObjectName("actionAujourd_hui")
        self.actionRe_ues = QtWidgets.QAction(MainWindow)
        self.actionRe_ues.setObjectName("actionRe_ues")
        self.actionDemain = QtWidgets.QAction(MainWindow)
        self.actionDemain.setObjectName("actionDemain")
        self.menuSupervision.addAction(self.actionMAINTENANT)
        self.menuSupervision.addAction(self.actionPREVIISIION)
        self.menuTableEchange.addAction(self.actionAujourd_hui)
        self.menuTableEchange.addAction(self.actionDemain)
        self.menuNotifications.addAction(self.actionRe_ues)
        self.menubar.addAction(self.menuSupervision.menuAction())
        self.menubar.addAction(self.menuTableEchange.menuAction())
        self.menubar.addAction(self.menuNotifications.menuAction())

        self.retranslateUi(MainWindow)
        self.MainStackWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.actionPREVIISIION.triggered.connect(self.goToPrediction)
        self.actionMAINTENANT.triggered.connect(self.goToSupervision)
        self.actionAujourd_hui.triggered.connect(self.goToTodayExchangeTable)
        self.actionDemain.triggered.connect(self.goToTomorrowExchangeTable)
        self.actionRe_ues.triggered.connect(self.goToNotifications)
        self.planificationButton.clicked.connect(self.goToPlanning)
        #{self.pushButton.clicked.connect(self.executeDemo)
        self.todayTableWidget.itemClicked.connect(self.goToTodayContractDetails)
        self.tableWidget.itemClicked.connect(self.goToTomorrowContractDetails)

            
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginbt.setText(_translate("MainWindow", "Login"))
        self.label_10.setText(_translate("MainWindow", "Password"))
        self.label_12.setText(_translate("MainWindow", "Home Energy Monitor"))
        self.label.setText(_translate("MainWindow", "Login"))
        self.exitAppbtn.setText(_translate("MainWindow", "Exit"))
        self.label_11.setText(_translate("MainWindow", "Solde de compte:"))
        self.solde.setText(_translate("MainWindow", "0            AU"))
        self.bienvenue.setText(_translate("MainWindow", "Bienvenue Prénom!"))
        self.label_81.setText(_translate("MainWindow", "Mode:"))
        self.mode.setText(_translate("MainWindow", "Consumer ()"))
        self.Localisation.setText(_translate("MainWindow", "Sfax"))
        self.hour.setText(_translate("MainWindow", "à  15h:30"))
        self.label_2.setText(_translate("MainWindow", "Panneaux PhotoVoltaiques"))
        self.label_7.setText(_translate("MainWindow", "Puissance Produite:"))
        self.label_8.setText(_translate("MainWindow", "W"))
        self.label_106.setText(_translate("MainWindow", "°C"))
        self.description.setText(_translate("MainWindow", "Clear sky"))
        self.humidity.setText(_translate("MainWindow", "<html><head/><body><p>Irradiance solaire : </p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "Météo du jour"))
        self.label1.setText(_translate("MainWindow", "<html><head/><body><p>68,7 w/m<span style=\" vertical-align:super;\">2</span></p></body></html>"))
        self.backbtn.setText(_translate("MainWindow", "Back"))
        self.label_67.setText(_translate("MainWindow", "Energie consommée"))
        self.label_74.setText(_translate("MainWindow", "Energie injectée"))
        self.label_77.setText(_translate("MainWindow", "Wh"))
        self.label_82.setText(_translate("MainWindow", "Wh"))
        self.label_78.setText(_translate("MainWindow", "<html><head/><body><p>Échanges avec la communauté</p></body></html>"))
        self.label_92.setText(_translate("MainWindow", "W"))
        self.label_85.setText(_translate("MainWindow", "<html><head/><body><p>Échanges avec le grid</p></body></html>"))
        self.label_88.setText(_translate("MainWindow", "Puissance injectée:"))
        self.label_24.setText(_translate("MainWindow", "Puissance consommée:"))
        self.label_34.setText(_translate("MainWindow", "W"))
        self.label_3.setText(_translate("MainWindow", "Prévison météo à 24h:"))
        self.label_5.setText(_translate("MainWindow", "Prévision des flux d\'énergie sur 24h"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Sfax, journée ensoleillée</span></p></body></html>"))
        self.planificationButton.setText(_translate("MainWindow", "Autoriser la planification \n"
"des échanges"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p>Planification des échanges</p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Balance énergétique en Wh:<br/>(énergie injectée - énergie consommée)</span></p></body></html>"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Heure"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Échange avec"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mode"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Contracts"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "1h"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "2h"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "3h"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "4h"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "5h "))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "6h"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("MainWindow", "7h"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("MainWindow", "8h"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("MainWindow", "9h"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("MainWindow", "10h"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("MainWindow", "11h"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("MainWindow", "12h"))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("MainWindow", "13h"))
        item = self.tableWidget.item(13, 0)
        item.setText(_translate("MainWindow", "14h"))
        item = self.tableWidget.item(14, 0)
        item.setText(_translate("MainWindow", "15h"))
        item = self.tableWidget.item(15, 0)
        item.setText(_translate("MainWindow", "16h"))
        item = self.tableWidget.item(16, 0)
        item.setText(_translate("MainWindow", "17h"))
        item = self.tableWidget.item(17, 0)
        item.setText(_translate("MainWindow", "18h"))
        item = self.tableWidget.item(18, 0)
        item.setText(_translate("MainWindow", "19h"))
        item = self.tableWidget.item(19, 0)
        item.setText(_translate("MainWindow", "20h"))
        item = self.tableWidget.item(20, 0)
        item.setText(_translate("MainWindow", "21h"))
        item = self.tableWidget.item(21, 0)
        item.setText(_translate("MainWindow", "22h"))
        item = self.tableWidget.item(22, 0)
        item.setText(_translate("MainWindow", "23h "))
        item = self.tableWidget.item(23, 0)
        item.setText(_translate("MainWindow", "24h"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_15.setText(_translate("MainWindow", "Table d\'échange de Demain"))
        self.label_19.setText(_translate("MainWindow", "Détails du Contract(s)"))
        self.label_30.setText(_translate("MainWindow", "Table d\'échange d\'Aujourd\'hui"))
        item = self.todayTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Instant"))
        item = self.todayTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Échange avec"))
        item = self.todayTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mode"))
        item = self.todayTableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Contracts"))
        __sortingEnabled = self.todayTableWidget.isSortingEnabled()
        self.todayTableWidget.setSortingEnabled(False)
        item = self.todayTableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "t=1"))
        item = self.todayTableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "t=2"))
        item = self.todayTableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "t=3"))
        item = self.todayTableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "t=4"))
        item = self.todayTableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "t=5"))
        item = self.todayTableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "t=6"))
        item = self.todayTableWidget.item(6, 0)
        item.setText(_translate("MainWindow", "t=7"))
        item = self.todayTableWidget.item(7, 0)
        item.setText(_translate("MainWindow", "t=8"))
        item = self.todayTableWidget.item(8, 0)
        item.setText(_translate("MainWindow", "t=9"))
        item = self.todayTableWidget.item(9, 0)
        item.setText(_translate("MainWindow", "t=10"))
        item = self.todayTableWidget.item(10, 0)
        item.setText(_translate("MainWindow", "t=11"))
        item = self.todayTableWidget.item(11, 0)
        item.setText(_translate("MainWindow", "t=12"))
        item = self.todayTableWidget.item(12, 0)
        item.setText(_translate("MainWindow", "t=13"))
        item = self.todayTableWidget.item(13, 0)
        item.setText(_translate("MainWindow", "t=14"))
        item = self.todayTableWidget.item(14, 0)
        item.setText(_translate("MainWindow", "t=15"))
        item = self.todayTableWidget.item(15, 0)
        item.setText(_translate("MainWindow", "t=16"))
        item = self.todayTableWidget.item(16, 0)
        item.setText(_translate("MainWindow", "t=17"))
        item = self.todayTableWidget.item(17, 0)
        item.setText(_translate("MainWindow", "t=18"))
        item = self.todayTableWidget.item(18, 0)
        item.setText(_translate("MainWindow", "t=19"))
        item = self.todayTableWidget.item(19, 0)
        item.setText(_translate("MainWindow", "t=20"))
        item = self.todayTableWidget.item(20, 0)
        item.setText(_translate("MainWindow", "t=21"))
        item = self.todayTableWidget.item(21, 0)
        item.setText(_translate("MainWindow", "t=22"))
        item = self.todayTableWidget.item(22, 0)
        item.setText(_translate("MainWindow", "t=23"))
        item = self.todayTableWidget.item(23, 0)
        item.setText(_translate("MainWindow", "t=24"))
        self.todayTableWidget.setSortingEnabled(__sortingEnabled)
        self.label_31.setText(_translate("MainWindow", "Puissance injectée (w):"))
        self.label_14.setText(_translate("MainWindow", "Puissance consommée (w):"))
        self.label_32.setText(_translate("MainWindow", "TextLabel"))
        self.label_33.setText(_translate("MainWindow", "Détail du contract(s)"))
        self.label_16.setText(_translate("MainWindow", "Liste des notifications"))
        self.menuSupervision.setTitle(_translate("MainWindow", "Suivi d\'énergie"))
        self.menuTableEchange.setTitle(_translate("MainWindow", "Échange d\'energie"))
        self.menuNotifications.setTitle(_translate("MainWindow", "Notifications"))
        self.actionMAINTENANT.setText(_translate("MainWindow", "Temps réel"))
        self.actionPREVIISIION.setText(_translate("MainWindow", "Prévisions"))
        self.actionAujourd_hui.setText(_translate("MainWindow", "Aujourd\'hui"))
        self.actionRe_ues.setText(_translate("MainWindow", "Reçues"))
        self.actionDemain.setText(_translate("MainWindow", "Demain"))
    
    def goToTodayContractDetails(self):
        indexes = self.todayTableWidget.selectionModel().selectedRows()
        for index in sorted(indexes): 
            print('contract id is selected' + self.todayTableWidget.item(index.row(), 3).text())
            idContracts=self.todayTableWidget.item( index.row(), 3).text()
            idContract=idContracts.split(",")[0]
            Scheduling.getSelectedContract(self, idContract,self.contractlistView)
    def goToTomorrowContractDetails(self):
        indexes = self.tableWidget.selectionModel().selectedRows()
        for index in sorted(indexes): 
            print('contract id is selected' + self.tableWidget.item(index.row(), 3).text())
            idContracts=self.tableWidget.item( index.row(), 3).text()
            idContract=idContracts.split(",")[0]
            Scheduling.getSelectedContract(self, idContract, self.contractslistView)
            
    def doit(self):
        print ("Opening a new popup window...")
        """self.splash=QSplashScreen(QtGui.QPixmap('./images/localisation.jpg'))
        self.splash.showMessage( "nouvelle notification", Qt.AlignTop | Qt.AlignLeft )
        self.splash.show()"""
        self.splashLabel = QtWidgets.QWidget()
        self.splashLabel.setWindowFlags(Qt.SplashScreen | Qt.FramelessWindowHint)
        #self.setWindowFlags(Qt.FramelessWindowHint | Qt.WindowStaysOnTopHint)
        resolution = QDesktopWidget().screenGeometry(-1)
        screenWidth = resolution.width()
        screenHeight = resolution.height()
        print("width: " + str (self.MainStackWidget.x()) + " height: " + str(resolution.height()))
        self.splashLabel.setGeometry(QRect(0, 0, 300, 51))
        self.splashLabel.show()
        #self.w.setGeometry(QRect(0, 0, 341, 51))
        #self.splash.move(10,10)
        #self.w.setParent(self.centralwidget)
        #self.w.setWindowFlags(QtCore.Qt.CustomizeWindowHint)
        """self.w = MyPopup()
        self.w.setWindowFlags(QtCore.Qt.SplashScreen)
        self.w.messageLabel = QLabel("nouvelle notification", self.w)
        self.w.messageLabel.setStyleSheet(
            "font-family: 'Roboto', sans-serif; font-size: 12px; font-weight: normal; padding: 0;")
        self.w.show()"""
        # Close SplashScreen after 3 seconds (3000 ms)
        QTimer.singleShot(3000, self.splashLabel.close)
        #QtWidgets.QMessageBox.information(self, 'Error', str(msg)+'\t \t \t \t \t')
        """msg = QMessageBox()
        msg.setWindowTitle("")
        msg.setText("This is the main text!")
        x = msg.exec_()"""
     
    def goToSupervision (self):     
        self.MainStackWidget.setCurrentIndex(1)
        
        Supervision.updateSole(self)
        
    def goToPrediction (self):
        self.MainStackWidget.setCurrentIndex(2)
        Prediction.goToPrediction(self)
        
    def goToTodayExchangeTable (self):
        self.MainStackWidget.setCurrentIndex(4)
        Scheduling.goToTodayExchangeTable(self, "files/toDayExchange.txt")
        #Scheduling.goToContracts(self,self.listView)
    def goToTomorrowExchangeTable (self):
        self.MainStackWidget.setCurrentIndex(3)
        Scheduling.goToTomorrowExchangeTable(self, "files/tomorrowExchange.txt")
        #Scheduling.goToContracts(self,self.contractslistView)

    def goToNotifications (self):
        entries = ['one\n ones','two', 'three']
        model = QtGui.QStandardItemModel()
        for i in entries:
            item = QtGui.QStandardItem(i)
            model.appendRow(item)
        #self.notificationslistView.addItems(entries)
        self.notificationslistView.setModel(model)
        #self.notificationslistView.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.MainStackWidget.setCurrentIndex(5)
    def goToPlanning(self):
        Prediction.planningOffersRequests(self)
        
    def executeDemo(self):
        Scheduling.executeDemo(self,"files/toDayExchange.txt")
    
    def showTime(self):
        currentTime = QTime.currentTime()
        displayTxt = currentTime.toString('hh:mm')
        _translate = QtCore.QCoreApplication.translate
        self.hour.setText(_translate("MainWindow", "à  "+displayTxt))
