# -*- coding: utf-8 -*-
import sys
from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5.QtWidgets import QMessageBox
import paramiko
import time
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import os
import math
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as Canvas
from matplotlib.figure import Figure
from PyQt5.QtGui import QTextCursor
from pip._internal import req
import requests

import json
import Scheduling, Supervision, GenericExchangePlace, Prediction

global dataEnv
with open("./files/env.json") as json_file:
    dataEnv = json.load(json_file)
    
uifile_1 = 'login.ui'
form_1, base_1 = uic.loadUiType(uifile_1)
uifile_2 = 'Exchange.ui'
form_2, base_2 = uic.loadUiType(uifile_2)
import images_rc

##############

class MplCanvas(Canvas):
    def __init__(self):
        self.fig = Figure()
        self.ax = self.fig.add_subplot(111)
        Canvas.__init__(self, self.fig)
        Canvas.setSizePolicy(self, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        Canvas.updateGeometry(self)

#----------------------------------------
#----------------------------------------
        
class MplWidget(QtWidgets.QWidget):
    def __init__(self, parent=None):
        QtWidgets.QWidget.__init__(self, parent)   
        self.canvas = MplCanvas()                  
        self.vbl = QtWidgets.QVBoxLayout()         
        self.vbl.addWidget(self.canvas)
        self.setLayout(self.vbl)
######################################

class MyPopup(QWidget):
    def __init__(self):
        QWidget.__init__(self)

    """def paintEvent(self, e):
        dc = QPainter(self)
        dc.drawLine(0, 0, 100, 100)
        dc.drawLine(100, 0, 0, 100)"""

class Exchange(base_2, form_2):
    consumption=[]
    production=[]
    __instance = None
    def __init__(self):
        """ Virtually private constructor. """
        if Exchange.__instance != None:
            raise Exception("This class is a singleton!")
        else:
            super(base_2, self).__init__()
            self.setupUi(self) 
            Supervision.weather_data(self)
            Supervision.balance(self)
        Exchange.__instance = self

    @staticmethod 
    def getInstance():
        """ Static access method. """
        if Exchange.__instance == None:
            Exchange()
        return Exchange.__instance 

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.MainStackWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.MainStackWidget.setGeometry(QtCore.QRect(0, 0, 1024, 600))
        self.MainStackWidget.setMinimumSize(QtCore.QSize(1024, 600))
        self.MainStackWidget.setMaximumSize(QtCore.QSize(1024, 600))
        self.MainStackWidget.setStyleSheet("background-color: rgb(255, 255, 255);color: rgb(255, 255, 255);")
        self.MainStackWidget.setMidLineWidth(1)
        self.MainStackWidget.setObjectName("MainStackWidget")
        self.page_0 = QtWidgets.QWidget()
        self.page_0.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.page_0.setObjectName("page_0")
        self.login = QtWidgets.QLineEdit(self.page_0)
        self.login.setGeometry(QtCore.QRect(200, 400, 250, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.login.setFont(font)
        self.login.setStyleSheet("border-radius: 15px;\n"
"border: 2px solid gray;\n"
"background-color: rgb(226, 226, 226);")
        self.login.setObjectName("login")
        self.loginbt = QtWidgets.QPushButton(self.page_0)
        self.loginbt.setGeometry(QtCore.QRect(650, 500, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(22)
        self.loginbt.setFont(font)
        self.loginbt.setStyleSheet("background-color: rgb(56, 125, 197);\n"
"border-radius: 20px;\n"
"color: rgb(255, 255, 255);")
        self.loginbt.setObjectName("loginbt")
        self.label_10 = QtWidgets.QLabel(self.page_0)
        self.label_10.setGeometry(QtCore.QRect(510, 400, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(22)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_12 = QtWidgets.QLabel(self.page_0)
        self.label_12.setGeometry(QtCore.QRect(212, 250, 600, 100))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(48)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.label = QtWidgets.QLabel(self.page_0)
        self.label.setGeometry(QtCore.QRect(50, 400, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.password = QtWidgets.QLineEdit(self.page_0)
        self.password.setGeometry(QtCore.QRect(710, 400, 250, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.password.setFont(font)
        self.password.setStyleSheet("border-radius: 15px;\n"
"border: 2px solid gray;\n"
"background-color: rgb(226, 226, 226);")
        self.password.setObjectName("password")
        self.label_18 = QtWidgets.QLabel(self.page_0)
        self.label_18.setGeometry(QtCore.QRect(730, 40, 250, 150))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap("E:\\AppEMTS\\EMTS_AutomaticMode\\images/sofrecomlogo.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.label_13 = QtWidgets.QLabel(self.page_0)
        self.label_13.setGeometry(QtCore.QRect(50, 40, 250, 150))
        self.label_13.setText("")
        self.label_13.setPixmap(QtGui.QPixmap("E:\\AppEMTS\\EMTS_AutomaticMode\\images/centrelogo.jpg"))
        self.label_13.setScaledContents(True)
        self.label_13.setObjectName("label_13")
        self.exitAppbtn = QtWidgets.QPushButton(self.page_0)
        self.exitAppbtn.setGeometry(QtCore.QRect(810, 500, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(22)
        self.exitAppbtn.setFont(font)
        self.exitAppbtn.setStyleSheet("background-color: rgb(56, 125, 197);\n"
"border-radius: 20px;\n"
"color: rgb(255, 255, 255);")
        self.exitAppbtn.setObjectName("exitAppbtn")
        self.MainStackWidget.addWidget(self.page_0)
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.SolarPanel = QtWidgets.QWidget(self.page_1)
        self.SolarPanel.setGeometry(QtCore.QRect(10, 98, 341, 201))
        self.SolarPanel.setStyleSheet("background-color: rgb(255, 255, 255);border:2px solid rgb(125, 172, 56);")
        self.SolarPanel.setObjectName("SolarPanel")
        self.solarIMG = QtWidgets.QLabel(self.SolarPanel)
        self.solarIMG.setGeometry(QtCore.QRect(220, 40, 91, 71))
        self.solarIMG.setStyleSheet("border:1px solid rgb(255, 255, 255);")
        self.solarIMG.setText("")
        self.solarIMG.setPixmap(QtGui.QPixmap("E:\\AppEMTS\\EMTS_AutomaticMode\\images/solar.png"))
        self.solarIMG.setScaledContents(True)
        self.solarIMG.setObjectName("solarIMG")
        self.label_2 = QtWidgets.QLabel(self.SolarPanel)
        self.label_2.setGeometry(QtCore.QRect(7, 10, 291, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.label_2.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"border:3px solid white;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setIndent(-2)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(self.SolarPanel)
        self.label_7.setGeometry(QtCore.QRect(10, 60, 81, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color:rgb(0, 0, 127);border:1px solid rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.pvPower = QtWidgets.QLCDNumber(self.SolarPanel)
        self.pvPower.setGeometry(QtCore.QRect(3, 104, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pvPower.setFont(font)
        self.pvPower.setStyleSheet("color:rgb(0, 0, 0);border:1px solid rgb(255, 255, 255);")
        self.pvPower.setDigitCount(6)
        self.pvPower.setProperty("value", 1550.55)
        self.pvPower.setObjectName("pvPower")
        self.label_8 = QtWidgets.QLabel(self.SolarPanel)
        self.label_8.setGeometry(QtCore.QRect(146, 122, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color:rgb(0, 0, 0);border:1px solid rgb(255, 255, 255);")
        self.label_8.setObjectName("label_8")
        self.Battery = QtWidgets.QWidget(self.page_1)
        self.Battery.setGeometry(QtCore.QRect(10, 310, 341, 241))
        self.Battery.setStyleSheet("background-color: rgb(255, 255, 255);border:2px solid rgb(125, 172, 56);")
        self.Battery.setObjectName("Battery")
        self.batIMG = QtWidgets.QLabel(self.Battery)
        self.batIMG.setGeometry(QtCore.QRect(219, 30, 101, 101))
        self.batIMG.setStyleSheet("border:0px ;")
        self.batIMG.setText("")
        self.batIMG.setPixmap(QtGui.QPixmap("E:\\AppEMTS\\EMTS_AutomaticMode\\images/battery3.png"))
        self.batIMG.setScaledContents(True)
        self.batIMG.setObjectName("batIMG")
        self.label_69 = QtWidgets.QLabel(self.Battery)
        self.label_69.setGeometry(QtCore.QRect(20, 10, 171, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_69.setFont(font)
        self.label_69.setStyleSheet("color:  rgb(0, 0, 0);border:0px ;")
        self.label_69.setObjectName("label_69")
        self.label_65 = QtWidgets.QLabel(self.Battery)
        self.label_65.setGeometry(QtCore.QRect(140, 80, 30, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.label_65.setObjectName("label_65")
        self.batterieLevel = QtWidgets.QLCDNumber(self.Battery)
        self.batterieLevel.setGeometry(QtCore.QRect(4, 50, 120, 60))
        self.batterieLevel.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.batterieLevel.setDigitCount(4)
        self.batterieLevel.setProperty("value", 85.0)
        self.batterieLevel.setObjectName("batterieLevel")
        self.batteriePower = QtWidgets.QLCDNumber(self.Battery)
        self.batteriePower.setGeometry(QtCore.QRect(11, 154, 101, 31))
        self.batteriePower.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.batteriePower.setDigitCount(7)
        self.batteriePower.setProperty("value", 425.0)
        self.batteriePower.setObjectName("batteriePower")
        self.label_41 = QtWidgets.QLabel(self.Battery)
        self.label_41.setGeometry(QtCore.QRect(130, 160, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.label_41.setObjectName("label_41")
        self.label_28 = QtWidgets.QLabel(self.Battery)
        self.label_28.setGeometry(QtCore.QRect(10, 120, 101, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: rgb(49, 112, 175);border:0px ;")
        self.label_28.setObjectName("label_28")
        self.line = QtWidgets.QFrame(self.page_1)
        self.line.setGeometry(QtCore.QRect(700, 0, 10, 600))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.weather = QtWidgets.QWidget(self.page_1)
        self.weather.setGeometry(QtCore.QRect(360, 99, 341, 201))
        self.weather.setStyleSheet("background-color: rgb(255, 255, 255);border:2px solid rgb(125, 172, 56);")
        self.weather.setObjectName("weather")
        self.WeatherImage = QtWidgets.QLabel(self.weather)
        self.WeatherImage.setGeometry(QtCore.QRect(40, 80, 41, 41))
        self.WeatherImage.setStyleSheet("border:0px ;")
        self.WeatherImage.setText("")
        self.WeatherImage.setPixmap(QtGui.QPixmap("E:\\AppEMTS\\EMTS_AutomaticMode\\images/01d.png"))
        self.WeatherImage.setScaledContents(True)
        self.WeatherImage.setObjectName("WeatherImage")
        self.label_106 = QtWidgets.QLabel(self.weather)
        self.label_106.setGeometry(QtCore.QRect(240, 80, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_106.setFont(font)
        self.label_106.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.label_106.setObjectName("label_106")
        self.temperature = QtWidgets.QLCDNumber(self.weather)
        self.temperature.setGeometry(QtCore.QRect(180, 90, 61, 41))
        self.temperature.setStyleSheet("color:rgb(0, 0, 0);border:0px ;")
        self.temperature.setDigitCount(2)
        self.temperature.setProperty("value", 30.0)
        self.temperature.setObjectName("temperature")
        self.Localisation = QtWidgets.QLabel(self.weather)
        self.Localisation.setGeometry(QtCore.QRect(38, 43, 91, 30))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.Localisation.setFont(font)
        self.Localisation.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.Localisation.setAlignment(QtCore.Qt.AlignCenter)
        self.Localisation.setObjectName("Localisation")
        self.description = QtWidgets.QLabel(self.weather)
        self.description.setGeometry(QtCore.QRect(27, 130, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.description.setFont(font)
        self.description.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.description.setObjectName("description")
        self.humidity = QtWidgets.QLabel(self.weather)
        self.humidity.setGeometry(QtCore.QRect(18, 160, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.humidity.setFont(font)
        self.humidity.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.humidity.setAlignment(QtCore.Qt.AlignCenter)
        self.humidity.setObjectName("humidity")
        self.label_4 = QtWidgets.QLabel(self.weather)
        self.label_4.setGeometry(QtCore.QRect(18, 9, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 0, 0);border:0px;")
        self.label_4.setObjectName("label_4")
        self.hour = QtWidgets.QLabel(self.weather)
        self.hour.setGeometry(QtCore.QRect(138, 48, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Rounded MT Bold")
        font.setPointSize(18)
        self.hour.setFont(font)
        self.hour.setStyleSheet("color:rgb(0, 0, 0);border:0px ;")
        self.hour.setObjectName("hour")
        self.label_6 = QtWidgets.QLabel(self.weather)
        self.label_6.setGeometry(QtCore.QRect(19, 40, 31, 31))
        self.label_6.setStyleSheet("border:0px ;")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("E:\\AppEMTS\\EMTS_AutomaticMode\\images/loc.jpg"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.label1 = QtWidgets.QLabel(self.weather)
        self.label1.setGeometry(QtCore.QRect(180, 160, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label1.setFont(font)
        self.label1.setStyleSheet("color:black;border:0px;")
        self.label1.setObjectName("label1")
        self.backbtn = QtWidgets.QPushButton(self.page_1)
        self.backbtn.setGeometry(QtCore.QRect(910, 20, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Gill Sans MT")
        font.setPointSize(22)
        self.backbtn.setFont(font)
        self.backbtn.setStyleSheet("background-color:rgb(121, 121, 121);border-radius: 20px;color: rgb(255, 255, 255);")
        self.backbtn.setObjectName("backbtn")
        self.Grid = QtWidgets.QWidget(self.page_1)
        self.Grid.setGeometry(QtCore.QRect(710, 98, 301, 451))
        self.Grid.setStyleSheet("background-color: rgb(255, 255, 255);border:2px solid rgb(125, 172, 56);")
        self.Grid.setObjectName("Grid")
        self.gridIMG = QtWidgets.QLabel(self.Grid)
        self.gridIMG.setGeometry(QtCore.QRect(170, 60, 111, 91))
        self.gridIMG.setStyleSheet("border:0px ;")
        self.gridIMG.setText("")
        self.gridIMG.setPixmap(QtGui.QPixmap("E:\\AppEMTS\\EMTS_AutomaticMode\\images/consCollective.png"))
        self.gridIMG.setScaledContents(True)
        self.gridIMG.setObjectName("gridIMG")
        self.label_67 = QtWidgets.QLabel(self.Grid)
        self.label_67.setGeometry(QtCore.QRect(20, 240, 171, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_67.setFont(font)
        self.label_67.setStyleSheet("color: rgb(0, 0, 127);border:0px ;")
        self.label_67.setObjectName("label_67")
        self.label_74 = QtWidgets.QLabel(self.Grid)
        self.label_74.setGeometry(QtCore.QRect(20, 160, 171, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_74.setFont(font)
        self.label_74.setStyleSheet("color: rgb(0, 0, 127);border:0px ;")
        self.label_74.setObjectName("label_74")
        self.outgoingPower = QtWidgets.QLCDNumber(self.Grid)
        self.outgoingPower.setGeometry(QtCore.QRect(10, 280, 90, 25))
        self.outgoingPower.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.outgoingPower.setDigitCount(7)
        self.outgoingPower.setProperty("value", 0.0)
        self.outgoingPower.setObjectName("outgoingPower")
        self.ingoingPower = QtWidgets.QLCDNumber(self.Grid)
        self.ingoingPower.setGeometry(QtCore.QRect(10, 190, 90, 25))
        self.ingoingPower.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.ingoingPower.setDigitCount(7)
        self.ingoingPower.setProperty("value", 0.0)
        self.ingoingPower.setObjectName("ingoingPower")
        self.label_77 = QtWidgets.QLabel(self.Grid)
        self.label_77.setGeometry(QtCore.QRect(120, 280, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_77.setFont(font)
        self.label_77.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.label_77.setObjectName("label_77")
        self.label_81 = QtWidgets.QLabel(self.Grid)
        self.label_81.setGeometry(QtCore.QRect(20, 80, 111, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_81.setFont(font)
        self.label_81.setStyleSheet("color: rgb(0, 0, 127);border:0px ;")
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(self.Grid)
        self.label_82.setGeometry(QtCore.QRect(120, 192, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_82.setFont(font)
        self.label_82.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.label_82.setObjectName("label_82")
        self.label_76 = QtWidgets.QLabel(self.Grid)
        self.label_76.setGeometry(QtCore.QRect(40, 10, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_76.setFont(font)
        self.label_76.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.label_76.setObjectName("label_76")
        self.mode = QtWidgets.QLabel(self.Grid)
        self.mode.setGeometry(QtCore.QRect(40, 120, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setItalic(False)
        self.mode.setFont(font)
        self.mode.setStyleSheet("border:0px ;color: rbg(0,0,0);")
        self.mode.setObjectName("mode")
        self.label_11 = QtWidgets.QLabel(self.Grid)
        self.label_11.setGeometry(QtCore.QRect(30, 340, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(0, 0, 127);border:0px ;")
        self.label_11.setObjectName("label_11")
        self.solde = QtWidgets.QLCDNumber(self.Grid)
        self.solde.setGeometry(QtCore.QRect(21, 380, 91, 23))
        self.solde.setStyleSheet("color:rgb(0, 0, 0);border:0px ;")
        self.solde.setObjectName("solde")
        self.label_14 = QtWidgets.QLabel(self.Grid)
        self.label_14.setGeometry(QtCore.QRect(130, 382, 47, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color:rgb(0, 0, 0);border:0px ;")
        self.label_14.setObjectName("label_14")
        self.Home = QtWidgets.QWidget(self.page_1)
        self.Home.setGeometry(QtCore.QRect(360, 310, 341, 241))
        self.Home.setStyleSheet("background-color: rgb(255, 255, 255);border:2px solid rgb(125, 172, 56);")
        self.Home.setObjectName("Home")
        self.label_92 = QtWidgets.QLabel(self.Home)
        self.label_92.setGeometry(QtCore.QRect(157, 120, 21, 25))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_92.setFont(font)
        self.label_92.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.label_92.setObjectName("label_92")
        self.houseIMG = QtWidgets.QLabel(self.Home)
        self.houseIMG.setGeometry(QtCore.QRect(220, 30, 100, 80))
        self.houseIMG.setStyleSheet("border-color: rgb(255, 255, 255);")
        self.houseIMG.setText("")
        self.houseIMG.setPixmap(QtGui.QPixmap("E:\\AppEMTS\\EMTS_AutomaticMode\\images/house.png"))
        self.houseIMG.setScaledContents(True)
        self.houseIMG.setObjectName("houseIMG")
        self.label_85 = QtWidgets.QLabel(self.Home)
        self.label_85.setGeometry(QtCore.QRect(20, 10, 161, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_85.setFont(font)
        self.label_85.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.label_85.setObjectName("label_85")
        self.label_88 = QtWidgets.QLabel(self.Home)
        self.label_88.setGeometry(QtCore.QRect(20, 60, 101, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_88.setFont(font)
        self.label_88.setStyleSheet("color: rgb(0, 0, 127);border:0px ;")
        self.label_88.setObjectName("label_88")
        self.consommationPower = QtWidgets.QLCDNumber(self.Home)
        self.consommationPower.setGeometry(QtCore.QRect(25, 108, 111, 41))
        self.consommationPower.setStyleSheet("color: rgb(0, 0, 0);border:0px ;")
        self.consommationPower.setDigitCount(6)
        self.consommationPower.setProperty("value", 300.25)
        self.consommationPower.setObjectName("consommationPower")
        self.label_17 = QtWidgets.QLabel(self.page_1)
        self.label_17.setGeometry(QtCore.QRect(0, 0, 1021, 91))
        self.label_17.setStyleSheet("background-image: url(:/images/banniere1.png);")
        self.label_17.setText("")
        self.label_17.setScaledContents(True)
        self.label_17.setObjectName("label_17")
        self.MainStackWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.graphWidget = MplWidget(self.page_2)
        self.graphWidget.setGeometry(QtCore.QRect(40, 140, 681, 311))
        self.graphWidget.setObjectName("graphWidget")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(740, 110, 211, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(30, 100, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(self.page_2)
        self.label_9.setGeometry(QtCore.QRect(754, 240, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_9.setObjectName("label_9")
        self.temperature_2 = QtWidgets.QLCDNumber(self.page_2)
        self.temperature_2.setGeometry(QtCore.QRect(839, 155, 81, 41))
        self.temperature_2.setStyleSheet("color:rgb(0, 0, 0); border:0px ;")
        self.temperature_2.setDigitCount(3)
        self.temperature_2.setProperty("value", 31.0)
        self.temperature_2.setProperty("intValue", 31)
        self.temperature_2.setObjectName("temperature_2")
        self.label_20 = QtWidgets.QLabel(self.page_2)
        self.label_20.setGeometry(QtCore.QRect(929, 165, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_20.setObjectName("label_20")
        self.irradiance = QtWidgets.QLabel(self.page_2)
        self.irradiance.setGeometry(QtCore.QRect(860, 290, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.irradiance.setFont(font)
        self.irradiance.setStyleSheet("color:rgb(0, 0, 0)")
        self.irradiance.setObjectName("irradiance")
        self.label_22 = QtWidgets.QLabel(self.page_2)
        self.label_22.setGeometry(QtCore.QRect(775, 167, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.page_2)
        self.label_23.setGeometry(QtCore.QRect(740, 160, 31, 31))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("E:\\AppEMTS\\EMTS_AutomaticMode\\images/loc.jpg"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        self.planificationButton = QtWidgets.QPushButton(self.page_2)
        self.planificationButton.setGeometry(QtCore.QRect(370, 510, 111, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.planificationButton.setFont(font)
        self.planificationButton.setStyleSheet("color:rgb(0, 0, 0); background-color:rgb(218, 218, 218);border-radius:5px;")
        self.planificationButton.setObjectName("planificationButton")
        self.label_21 = QtWidgets.QLabel(self.page_2)
        self.label_21.setGeometry(QtCore.QRect(30, 460, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_21.setObjectName("label_21")
        self.label_24 = QtWidgets.QLabel(self.page_2)
        self.label_24.setGeometry(QtCore.QRect(40, 500, 341, 51))
        self.label_24.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_24.setObjectName("label_24")
        self.label_26 = QtWidgets.QLabel(self.page_2)
        self.label_26.setGeometry(QtCore.QRect(0, 0, 1031, 91))
        self.label_26.setStyleSheet("background-image:url(:/images/banniere1.png)")
        self.label_26.setObjectName("label_26")
        self.MainStackWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.tableWidget = QtWidgets.QTableWidget(self.page_3)
        self.tableWidget.setGeometry(QtCore.QRect(50, 140, 381, 401))
        self.tableWidget.setStyleSheet("color:rgb(0, 0, 0);background-color:rgb(255, 255, 255);")
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setRowCount(25)
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(144, 144, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(144, 144, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(144, 144, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(15, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(16, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(17, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(18, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(19, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(20, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(21, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(22, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(23, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(24, 0, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(113)
        self.tableWidget.verticalHeader().setVisible(False)
        self.label_15 = QtWidgets.QLabel(self.page_3)
        self.label_15.setGeometry(QtCore.QRect(20, 100, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_15.setObjectName("label_15")
        self.label_19 = QtWidgets.QLabel(self.page_3)
        self.label_19.setGeometry(QtCore.QRect(501, 127, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(0, 0, 0)")
        self.label_19.setObjectName("label_19")
        self.contractslistView = QtWidgets.QListView(self.page_3)
        self.contractslistView.setGeometry(QtCore.QRect(520, 160, 421, 201))
        self.contractslistView.setStyleSheet("color:rgb(0, 0, 0)")
        self.contractslistView.setObjectName("contractslistView")
        self.getContractsBtn = QtWidgets.QPushButton(self.page_3)
        self.getContractsBtn.setGeometry(QtCore.QRect(834, 130, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.getContractsBtn.setFont(font)
        self.getContractsBtn.setStyleSheet("color:rgb(0, 0, 0);background-color:rgb(231, 231, 231);border-radius:3px;")
        self.getContractsBtn.setObjectName("getContractsBtn")
        self.label_25 = QtWidgets.QLabel(self.page_3)
        self.label_25.setGeometry(QtCore.QRect(0, 0, 1021, 91))
        self.label_25.setStyleSheet("background-image: url(:/images/banniere1.png);")
        self.label_25.setText("")
        self.label_25.setObjectName("label_25")
        self.executeBtn = QtWidgets.QPushButton(self.page_3)
        self.executeBtn.setGeometry(QtCore.QRect(640, 440, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.executeBtn.setFont(font)
        self.executeBtn.setStyleSheet("color:rgb(0, 0, 0);background-color:rgb(231, 231, 231);border-radius:4px;")
        self.executeBtn.setObjectName("executeBtn")
        self.MainStackWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.notificationslistView = QtWidgets.QListView(self.page_4)
        self.notificationslistView.setGeometry(QtCore.QRect(60, 70, 401, 461))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.notificationslistView.setFont(font)
        self.notificationslistView.setStyleSheet("background-color:rgb(255, 255, 255);color:rgb(0, 0, 0);")
        self.notificationslistView.setMidLineWidth(1)
        self.notificationslistView.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.notificationslistView.setObjectName("notificationslistView")
        self.label_16 = QtWidgets.QLabel(self.page_4)
        self.label_16.setGeometry(QtCore.QRect(30, 30, 211, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color:rgb(0, 0, 0)")
        self.label_16.setObjectName("label_16")
        self.MainStackWidget.addWidget(self.page_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        self.menuSupervision = QtWidgets.QMenu(self.menubar)
        self.menuSupervision.setObjectName("menuSupervision")
        self.menuTableEchange = QtWidgets.QMenu(self.menubar)
        self.menuTableEchange.setObjectName("menuTableEchange")
        self.menuNotifications = QtWidgets.QMenu(self.menubar)
        self.menuNotifications.setObjectName("menuNotifications")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionMAINTENANT = QtWidgets.QAction(MainWindow)
        self.actionMAINTENANT.setObjectName("actionMAINTENANT")
        self.actionPREVIISIION = QtWidgets.QAction(MainWindow)
        self.actionPREVIISIION.setObjectName("actionPREVIISIION")
        self.actionDemain = QtWidgets.QAction(MainWindow)
        self.actionDemain.setObjectName("actionDemain")
        self.actionRe_ues = QtWidgets.QAction(MainWindow)
        self.actionRe_ues.setObjectName("actionRe_ues")
        self.menuSupervision.addAction(self.actionMAINTENANT)
        self.menuSupervision.addAction(self.actionPREVIISIION)
        self.menuTableEchange.addAction(self.actionDemain)
        self.menuNotifications.addAction(self.actionRe_ues)
        self.menubar.addAction(self.menuSupervision.menuAction())
        self.menubar.addAction(self.menuTableEchange.menuAction())
        self.menubar.addAction(self.menuNotifications.menuAction())

        self.retranslateUi(MainWindow)
        self.MainStackWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
       
        self.actionPREVIISIION.triggered.connect(self.goToPrediction)
        self.actionMAINTENANT.triggered.connect(self.goToSupervision)
        self.actionDemain.triggered.connect(self.goToTableEchange)
        self.actionRe_ues.triggered.connect(self.goToNotifications)
        self.planificationButton.clicked.connect(self.goToPlanning)
       
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loginbt.setText(_translate("MainWindow", "Login"))
        self.label_10.setText(_translate("MainWindow", "Password"))
        self.label_12.setText(_translate("MainWindow", "Home Energy Monitor"))
        self.label.setText(_translate("MainWindow", "Login"))
        self.exitAppbtn.setText(_translate("MainWindow", "Exit"))
        self.label_2.setText(_translate("MainWindow", "Panneaux PhotoVoltaiques"))
        self.label_7.setText(_translate("MainWindow", "Puissance"))
        self.label_8.setText(_translate("MainWindow", "W"))
        self.label_69.setText(_translate("MainWindow", "Etat de la batterie"))
        self.label_65.setText(_translate("MainWindow", "%"))
        self.label_41.setText(_translate("MainWindow", "W"))
        self.label_28.setText(_translate("MainWindow", "Puissance"))
        self.label_106.setText(_translate("MainWindow", "°C"))
        self.Localisation.setText(_translate("MainWindow", "Sfax"))
        self.description.setText(_translate("MainWindow", "Clear sky"))
        self.humidity.setText(_translate("MainWindow", "<html><head/><body><p>Irradiance solaire : </p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "M�t�o du jour"))
        self.hour.setText(_translate("MainWindow", "�  15h:30"))
        self.label1.setText(_translate("MainWindow", "<html><head/><body><p>68,7 w/m<span style=\" vertical-align:super;\">2</span></p></body></html>"))
        self.backbtn.setText(_translate("MainWindow", "Back"))
        self.label_67.setText(_translate("MainWindow", "Energie tir�e du grid"))
        self.label_74.setText(_translate("MainWindow", "Energie inject�e au grid"))
        self.label_77.setText(_translate("MainWindow", "W"))
        self.label_81.setText(_translate("MainWindow", "Mode"))
        self.label_82.setText(_translate("MainWindow", "W"))
        self.label_76.setText(_translate("MainWindow", "<html><head/><body><p>Auto-consommation <br/>collective</p></body></html>"))
        self.mode.setText(_translate("MainWindow", "Autonome"))
        self.label_11.setText(_translate("MainWindow", "Solde de compte"))
        self.label_14.setText(_translate("MainWindow", "AU"))
        self.label_92.setText(_translate("MainWindow", "W"))
        self.label_85.setText(_translate("MainWindow", "Consommation"))
        self.label_88.setText(_translate("MainWindow", "Puissance"))
        self.label_3.setText(_translate("MainWindow", "Pr�vison m�t�o � 24h"))
        self.label_5.setText(_translate("MainWindow", "Pr�vision des flux d\'�nergie sur 24h"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>Irradiance solaire</p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "�C"))
        self.irradiance.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">68,7 w/m</span><span style=\" font-size:14pt; vertical-align:super;\">2</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Sfax</span></p></body></html>"))
        self.planificationButton.setText(_translate("MainWindow", "Ok"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p>Planification de l\'autoconsommation Collective</p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p>Echanger de l\'énergie verte produite localement: <br/>- Publier des offres en cas d\'exès d\'énergie<br/>- Publier des demandes en cas de manque d\'énergie<br/></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "TextLabel"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Intervalle "))
        item = self.tableWidget.item(0, 1)
        item.setText(_translate("MainWindow", "Mode"))
        item = self.tableWidget.item(0, 2)
        item.setText(_translate("MainWindow", "Contracts"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("MainWindow", "0h - 1h"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("MainWindow", "1h - 2h"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("MainWindow", "2h - 3h"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("MainWindow", "3h - 4h"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("MainWindow", "4h - 5h"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("MainWindow", "5h - 6h"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("MainWindow", "6h - 7h"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("MainWindow", "7h - 8h "))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("MainWindow", "8h - 9h"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("MainWindow", "9h - 10 h"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("MainWindow", "10h - 11h"))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("MainWindow", "11h -12h"))
        item = self.tableWidget.item(13, 0)
        item.setText(_translate("MainWindow", "12h - 13h"))
        item = self.tableWidget.item(14, 0)
        item.setText(_translate("MainWindow", "13h -14h"))
        item = self.tableWidget.item(15, 0)
        item.setText(_translate("MainWindow", "14h - 15h"))
        item = self.tableWidget.item(16, 0)
        item.setText(_translate("MainWindow", "15h - 16h"))
        item = self.tableWidget.item(17, 0)
        item.setText(_translate("MainWindow", "16h - 17h"))
        item = self.tableWidget.item(18, 0)
        item.setText(_translate("MainWindow", "17h - 18h"))
        item = self.tableWidget.item(19, 0)
        item.setText(_translate("MainWindow", "18h - 19h"))
        item = self.tableWidget.item(20, 0)
        item.setText(_translate("MainWindow", "19h - 20h"))
        item = self.tableWidget.item(21, 0)
        item.setText(_translate("MainWindow", "20h - 21h"))
        item = self.tableWidget.item(22, 0)
        item.setText(_translate("MainWindow", "21h - 22h"))
        item = self.tableWidget.item(23, 0)
        item.setText(_translate("MainWindow", "22h - 23h"))
        item = self.tableWidget.item(24, 0)
        item.setText(_translate("MainWindow", "23h - 24"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_15.setText(_translate("MainWindow", "Planification d\'échange"))
        self.label_19.setText(_translate("MainWindow", "Détails des Contracts"))
        self.getContractsBtn.setText(_translate("MainWindow", "Actualiser"))
        self.executeBtn.setText(_translate("MainWindow", "Exécuter la planification"))
        self.label_16.setText(_translate("MainWindow", "Liste des notifications"))
        self.menuSupervision.setTitle(_translate("MainWindow", "Suivi d\'énergie"))
        self.menuTableEchange.setTitle(_translate("MainWindow", "Table d\'échange"))
        self.menuNotifications.setTitle(_translate("MainWindow", "Notifications"))
        self.actionMAINTENANT.setText(_translate("MainWindow", "Temps réel"))
        self.actionPREVIISIION.setText(_translate("MainWindow", "Prévisions"))
        self.actionDemain.setText(_translate("MainWindow", "Demain"))
        self.actionRe_ues.setText(_translate("MainWindow", "Reçues"))

    
    
    def doit(self):
        print ("Opening a new popup window...")
        """self.splash=QSplashScreen(QtGui.QPixmap('./images/localisation.jpg'))
        self.splash.showMessage( "nouvelle notification", Qt.AlignTop | Qt.AlignLeft )
        self.splash.show()"""
        self.splashLabel = QtWidgets.QWidget()
        self.splashLabel.setWindowFlags(Qt.SplashScreen | Qt.FramelessWindowHint)
        #self.setWindowFlags(Qt.FramelessWindowHint | Qt.WindowStaysOnTopHint)
        resolution = QDesktopWidget().screenGeometry(-1)
        screenWidth = resolution.width()
        screenHeight = resolution.height()
        print("width: " + str (self.MainStackWidget.x()) + " height: " + str(resolution.height()))
        self.splashLabel.setGeometry(QRect(0, 0, 300, 51))
        self.splashLabel.show()
        #self.w.setGeometry(QRect(0, 0, 341, 51))
        #self.splash.move(10,10)
        #self.w.setParent(self.centralwidget)
        #self.w.setWindowFlags(QtCore.Qt.CustomizeWindowHint)
        """self.w = MyPopup()
        self.w.setWindowFlags(QtCore.Qt.SplashScreen)
        self.w.messageLabel = QLabel("nouvelle notification", self.w)
        self.w.messageLabel.setStyleSheet(
            "font-family: 'Roboto', sans-serif; font-size: 12px; font-weight: normal; padding: 0;")
        self.w.show()"""
        # Close SplashScreen after 3 seconds (3000 ms)
        QTimer.singleShot(3000, self.splashLabel.close)
        #QtWidgets.QMessageBox.information(self, 'Error', str(msg)+'\t \t \t \t \t')
        """msg = QMessageBox()
        msg.setWindowTitle("")
        msg.setText("This is the main text!")
        x = msg.exec_()"""
     
    def goToSupervision (self):     
        self.MainStackWidget.setCurrentIndex(1)
        #Supervision.weather_data(self)
        
    def goToPrediction (self):
        self.MainStackWidget.setCurrentIndex(2)
        Prediction.goToPrediction(self)
        
    def goToTableEchange (self):
        self.MainStackWidget.setCurrentIndex(3)
        Scheduling.goToTableEchange(self)
        Scheduling.goToContracts(self)

    def goToNotifications (self):
        entries = ['one\n ones','two', 'three']
        model = QtGui.QStandardItemModel()
        for i in entries:
            item = QtGui.QStandardItem(i)
            model.appendRow(item)
        self.notificationslistView.addItems(entries)
        self.notificationslistView.setModel(model)
        #self.notificationslistView.setStyleSheet("background-color:rgb(0, 0, 0);")
        self.MainStackWidget.setCurrentIndex(4)
    def goToPlanning(self):
        Prediction.planningOffersRequests(self)

